# Generated by Django 4.2.5 on 2023-09-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=8)),
                ('birth_date', models.DateField()),
                ('contact', models.CharField(max_length=15)),
                ('grade', models.CharField(max_length=30)),
            ],
        ),
    ]
