# Generated by Django 4.2.5 on 2023-09-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='address',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='officer',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
