# Generated by Django 4.2.5 on 2023-10-28 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0005_rename_client_id_clientpayment_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='client_id',
            new_name='client',
        ),
    ]
