# Generated by Django 4.2.5 on 2023-11-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officer', '0006_rename_client_id_deployment_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='photo',
            field=models.ImageField(default=0, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
